In [114]:
from setupDataset import get_dataset, save, load
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LassoCV
import numpy as np
import pandas as pd



m_devSet = get_dataset("M_DEV_dataset.pickle")
w_devSet = get_dataset("W_DEV_dataset.pickle")

In [161]:


def get_LassoSelections(dataset, out='SELECTIONS_lasso.pickle', step=0.005, maxThresh=0.25, minThresh=0.000005):
    X = dataset["data"]
    y = dataset["target"]
    
    thr_range =  np.arange(0.000005, 0.25, 0.005)
    no_selection = np.arange(0,68)
    
    selections = [no_selection]
    
    for thresh in thr_range:
        
        clf = LassoCV()
        sfm = SelectFromModel(clf, threshold=thresh)
        sfm.fit(X,y)
        sel = sfm.get_support(indices=True)
        n_features = sfm.transform(X).shape[1]
        
        if len(sel) > 0 and len(sel) != len(selections[-1]):
            selections.append(sel)
          
    selections.reverse()
    save(selections, out)
    return selections


def save_lassoDf(selections, out):
    df = pd.DataFrame({'selections': selections}) # df = pd.DataFrame({0: [[1,2,3],[3,4,5],[5,6,7]]})
    df.to_csv(out)
    return df

def load_lassoDf(file):
    df = pd.read_csv(file)
    sel = df.values
    return sel

In [160]:
from Utils.feature_ranking import load_rankSelections
mm = load('M_SELECTIONS_lasso.pickle')
mm

[array([40]),
 array([ 0, 40]),
 array([ 0,  5, 40]),
 array([ 0,  2,  5, 40]),
 array([ 0,  2,  5, 37, 40, 41, 44, 54]),
 array([ 0,  2,  5, 37, 40, 41, 42, 44, 46, 54]),
 array([ 0,  2,  5,  9, 37, 40, 41, 42, 44, 46, 54]),
 array([ 0,  1,  2,  5,  8,  9, 32, 37, 40, 41, 42, 44, 46, 51, 54, 61]),
 array([ 0,  1,  2,  5,  7,  8,  9, 12, 32, 34, 37, 39, 40, 41, 42, 44, 46,
        51, 54, 61]),
 array([ 0,  1,  2,  3,  5,  7,  8,  9, 12, 16, 32, 34, 37, 39, 40, 41, 42,
        44, 46, 51, 54, 61]),
 array([ 0,  1,  2,  3,  5,  7,  8,  9, 12, 16, 32, 34, 37, 39, 40, 41, 42,
        43, 44, 45, 46, 48, 51, 54, 55, 61]),
 array([ 0,  1,  2,  3,  5,  7,  8,  9, 12, 16, 18, 19, 20, 21, 32, 34, 37,
        39, 40, 41, 42, 43, 44, 45, 46, 48, 51, 54, 55, 61]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        

In [159]:
get_LassoSelections(m_devSet, out='M_SELECTIONS_lasso.pickle')

In [163]:
get_LassoSelections(w_devSet, out='W_SELECTIONS_lasso.pickle')

[array([7]),
 array([ 1,  7,  8,  9, 10, 16, 21, 37, 39, 40, 43, 46]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67])]

In [91]:
ws = get_LassoSelections(w_devSet)
print len(ws)
ws

2


[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67]),
 array([ 1,  7,  8,  9, 10, 16, 21, 37, 39, 40, 43, 46])]

In [77]:
type(ws)

numpy.ndarray

In [78]:
type(ws[1])

numpy.int64

In [81]:
len([ 0,  1,  2,  3,  5,  7,  8,  9, 12, 16, 18, 19, 20, 21, 32, 34, 37,
        39, 40, 41, 42, 43, 44, 45, 46, 48, 51, 54, 55, 61])

30

In [92]:
len([ 1,  7,  8,  9, 10, 16, 21, 37, 39, 40, 43, 46])

12

In [109]:
len([ 0,  1,  2,  3,  5,  7,  8,  9, 12, 16, 32, 34, 37, 39, 40, 41, 42,
        44, 46, 51, 54, 61])

22