In [1]:
%matplotlib inline
from __future__ import division
import matplotlib.pyplot as plt
from sklearn.feature_selection import chi2, f_classif, mutual_info_classif
import numpy as np
import pandas as pd
import scipy
from scipy import stats
from setupDataset import get_dataset
from feature_vector import get_feature_names
from model import compute_avg
fnames = get_feature_names()

def get_selectedFeatures(X, indices = []):
    # select column indices
    return X[:, indices]

/Users/nischikata/Documents/FHHGB/PycharmProjects/AggressivenessClassification/venv/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [9]:
first_selection = [0,1,4,7,10,11,12,13,16,18,19,20,21,23,24,26,31,32,33,34,35,36,40,43,53,54,56,58,59,60,61,62]
first_selection = [0,1,4,7,10,11,12,13,16,18,19,20,21,23,24,26,31,32,33,34,35,36,40,43,53,54,58,59,61,62]
wiki_f = [60,61,4,62,24,0,7,33,6,32,53,44,23,49,64,54,31,35,59,1,67,26,34,29,66,40,28,47,11,13,
         56, 36,19,12,51,18,20, # best from mi & ranksum
         16, 10, 43, 45, 21]#, best 10 from chi non overlap 5, 36, 30, 
          #14, 27, 56, 51, 10, 16, 21, 43, 45, 12, 18, 19, 20]

wiki_f = [40,61,4,62,24,0,7,33,6,32,53,44,23,49,64,54,31,35,59,1,67,26,34,29,66,28,47,11,13,
         36,19,12,51,18,20, # best from mi & ranksum
         16, 10, 43, 45, 21, 39]
    
wiki_ranksum = [60,56,40,1,51,12,62,7,13,18,19,33,20,32,6,24,10,4,43,41,57,23,48,54,31,14,0,36,44,64]

wiki_chi = [40,36,56,1,10,7,43,16,21,45,34,9,55,20,39,19,50,44,42,61,0,60,46,3,41,54,12,4,53,17]

wiki_mi = [60,56,40,7,1,51,61,62,24,12,13,32,36,19,4,33,6,10,23,18,0,41,35,26,59,31,57,58,43,46]
wiki_all = [40,36,56,1,10,7,43,16,21,45,34,9,55,20,39,19,50,44,42,61,0,60,46,3,41,54,12,4,53,17]
wiki_all = [40,36,56,1,10,7,43,16,21,45,34,9,55,20,39,19,50,44,42,61,0,46,3,41,54,12,4,53,17]

f = [1,43,40,10,59,11,26,35,56,24,60,62,0,61,2,12,18,34,19,20,46,53,58,52,54,47,42,3,23,4]
f = [1,43,40,10,59,11,26,35,24,62,0,61,2,12,18,34,19,20,46,53,58,52,54,47,42,3,23,4,39]
ranksum = [1,43,10,26,11,35,12,59,19,62,24,20,18,60,40,56,2,52,23,61,9,0,21,55,51,13,33,50,48,32]
chi = [43,10,1,18,20,19,40,34,8,16,3,56,46,2,7,47,54,21,42,0,12,53,38,61,36,55,66,45,9,17]
mi = [10,1,59,43,61,60,40,19,24,56,55,33,20,35,58,46,18,11,23,26,12,62,13,57,22,50,64,47,32,16]
dall = [43,10,1,40,59,18,19,56,20,24,11,60,35,26,61,62,12,2,0,34,55,46,23,33,47,52,58,16,54,13]
dall = [43,10,1,40,59,18,19,56,20,24,11,35,26,61,62,12,2,0,34,55,46,23,33,47,52,58,16,54,13,39]

a = set(set(wiki_mi[:15]) - set(wiki_f))
b = set(set(wiki_chi[:10]) - set(wiki_f))
c =  set(set(wiki_ranksum[:15]) - set(wiki_f))
print a
print b

#TODO combine set a und c und fuege es zu wiki_f hinzu

set([56, 60])
set([56])


In [10]:
dataset_wiki = get_dataset("wiki_dataset.pickle")
dataset = get_dataset("dataset.pickle")

# BEFORE FEATURE SELECTION


X_wiki = get_selectedFeatures(dataset_wiki["data"], first_selection)
y_wiki = dataset_wiki["target"]

# TODO finde verhaeltnis heraus von wiki target 0 vs 1 

X = get_selectedFeatures(dataset["data"], first_selection)
y = dataset["target"]

Xf = get_selectedFeatures(dataset["data"], wiki_f)
Xrank = get_selectedFeatures(dataset["data"], wiki_ranksum)
Xchi = get_selectedFeatures(dataset["data"], wiki_chi)
Xmi = get_selectedFeatures(dataset["data"], wiki_mi)
Xall = get_selectedFeatures(dataset["data"], wiki_all)

Xf_wiki = get_selectedFeatures(dataset_wiki["data"], wiki_f)
Xrank_wiki = get_selectedFeatures(dataset_wiki["data"], wiki_ranksum)
Xchi_wiki = get_selectedFeatures(dataset_wiki["data"], wiki_chi)
Xmi_wiki = get_selectedFeatures(dataset_wiki["data"], wiki_mi)
Xall_wiki = get_selectedFeatures(dataset_wiki["data"], wiki_all)

dXf = get_selectedFeatures(dataset["data"], f)
dXrank = get_selectedFeatures(dataset["data"], ranksum)
dXchi = get_selectedFeatures(dataset["data"], chi)
dXmi = get_selectedFeatures(dataset["data"], mi)
dXall = get_selectedFeatures(dataset["data"], dall)

dXf_wiki = get_selectedFeatures(dataset_wiki["data"], f)
dXrank_wiki = get_selectedFeatures(dataset_wiki["data"], ranksum)
dXchi_wiki = get_selectedFeatures(dataset_wiki["data"], chi)
dXmi_wiki = get_selectedFeatures(dataset_wiki["data"], mi)
dXall_wiki = get_selectedFeatures(dataset_wiki["data"], dall)


print "Wiki before feature selection"
compute_avg(dataset_wiki["data"], y_wiki, 100)
print "Wiki AFTER feature selection"
compute_avg(X_wiki, y_wiki, 100)

print "wiki f feature selection"
compute_avg(Xf_wiki, y_wiki, 100)
print "wiki d f feature selection"
compute_avg(dXf_wiki, y_wiki, 100)

print "Wiki ranksum feature selection"
compute_avg(Xrank_wiki, y_wiki, 100)
print "Wiki d ranksum feature selection"
compute_avg(dXrank_wiki, y_wiki, 100)

print "wiki chi feature selection"
compute_avg(Xchi_wiki, y_wiki, 100)
print "wiki d chi feature selection"
compute_avg(dXchi_wiki, y_wiki, 100)

print "Wiki mi feature selection"
compute_avg(Xmi_wiki, y_wiki, 100)
print "Wiki d mi feature selection"
compute_avg(dXmi_wiki, y_wiki, 100)

print "wiki all feature selection"
compute_avg(Xall_wiki, y_wiki, 100)
print "wiki dall feature selection"
compute_avg(dXall_wiki, y_wiki, 100)


print "\nBefore feature selection"
compute_avg(dataset["data"], y, 100)
print "AFTER feature selection"
compute_avg(X, y, 100)

print "f feature selection"
compute_avg(Xf, y, 100)
print "d f feature selection"
compute_avg(dXf, y, 100)

print "ranksum feature selection"
compute_avg(Xrank, y, 100)
print "d ranksum feature selection"
compute_avg(dXrank, y, 100)

print "chi feature selection"
compute_avg(Xchi, y, 100)
print "d chi feature selection"
compute_avg(dXchi, y, 100)

print "mi feature selection"
compute_avg(Xmi, y, 100)
print "d mi feature selection"
compute_avg(dXmi, y, 100)

print "all feature selection"
compute_avg(Xall, y, 100)
print "d all feature selection"
compute_avg(dXall, y, 100)









Wiki before feature selection
   recall 0.791259764696   precision:  0.915899343075    accuracy:  0.858452285485 f-score:  0.849029590022
[[ 57510.   4581.]
 [ 13070.  49539.]]
Wiki AFTER feature selection
   recall 0.776413869053   precision:  0.91819507752    accuracy:  0.852574178027 f-score:  0.841373337636
[[ 57682.   4363.]
 [ 14021.  48634.]]
wiki f feature selection
   recall 0.783927567186   precision:  0.914767879668    accuracy:  0.854995990377 f-score:  0.844308801529
[[ 57664.   4586.]
 [ 13496.  48954.]]
wiki d f feature selection
   recall 0.767322692705   precision:  0.910107376391    accuracy:  0.844282277466 f-score:  0.83263804026
[[ 57331.   4874.]
 [ 14544.  47951.]]
Wiki ranksum feature selection
   recall 0.768113179882   precision:  0.922409614994    accuracy:  0.851210906175 f-score:  0.8382199692
[[ 58122.   4052.]
 [ 14502.  48024.]]
Wiki d ranksum feature selection
   recall 0.725394815786   precision:  0.94844332416    accuracy:  0.842349639134 f-score:  0.

In [ ]:
for index, name in enumerate(fnames):
    print index, " ", name

In [23]:
np.bincount(y_wiki)

array([2488, 2500])

In [24]:
np.bincount(y)

array([520, 514])