In [1]:
from setupDataset import get_dataset, combine_datasets
from model import compute_avg
from feature_vector import get_feature_names

fnames = get_feature_names()


m_dataset = get_dataset("dataset.pickle")
w_dataset = get_dataset("wiki_dataset.pickle")

c_dataset = combine_datasets(m_dataset, w_dataset)

ym = m_dataset["target"]
yw = w_dataset["target"]
yc = c_dataset["target"]

rfe_d05 = [           11,     24,                                                                                59, 61, 62]
rfe_d10 = [        5, 11, 23, 24,                                     38, 40,                        53,     59, 61, 62]
rfe_d15 = [    4,  5, 11, 23, 24,     28,     33,                 38, 40,                47,     52, 53,     59, 61, 62]
rfe_d20 = [    4,  5, 11, 23, 24, 27, 28, 29, 33,                 38, 40,    42, 44,     47,     52, 53, 54, 59, 61, 62]
rfe_d25 = [    4,  5, 11, 23, 24, 27, 28, 29, 30, 33, 34,         38, 40,    42, 44, 45, 47,     52, 53, 54, 59, 61, 62, 64, 67]
rfe_d30 = [0,  4,  5, 11, 23, 24, 27, 28, 29, 30, 33, 34, 36, 37, 38, 40, 41,42, 44, 45, 47, 49, 52, 53, 54, 59, 61, 62, 64, 67]
rfe_d35 = [ 0,  1,  3,  4,  5,  8, 11, 14, 23, 24, 27, 28, 29, 30, 33, 34, 36,
       37, 38, 40, 41, 42, 44, 45, 47, 49, 52, 53, 54, 59, 61, 62, 64, 66,
       67]
rfe_d40 = [ 0,  1,  3,  4,  5,  7,  8, 11, 14, 22, 23, 24, 26, 27, 28, 29, 30,
       33, 34, 36, 37, 38, 40, 41, 42, 44, 45, 47, 49, 52, 53, 54, 58, 59,
       61, 62, 63, 64, 66, 67]

rfe_w15 = [ 0,  4,  5,     23, 24, 28,     32, 33, 35,     47, 56,     60, 61, 62, 64]
rfe_w20 = [ 0,  4,  5, 11, 23, 24, 28, 29, 32, 33, 35, 40, 47, 56, 59, 60, 61, 62, 64, 67]
rfe_w25 = [ 0,  4,  5, 11, 15, 22, 23, 24, 28, 29, 32, 33, 35, 40, 44, 45, 47, 56, 58, 59, 60, 61, 62, 64, 67]
rfe_w30 = [ 0,  4,  5,  7, 11, 17, 22, 23, 24, 28, 29, 32, 33, 35, 38, 40, 44,45, 47, 49, 52, 53, 56, 59, 60, 61, 62, 64, 66, 67]
rfe_w35 =[  0,  2,  3,  4,  5,  7, 17, 22, 23, 24, 26, 28, 29, 32, 33, 34, 35,38, 40, 44, 45, 47, 49, 50, 51, 52, 54, 56, 59, 60, 61, 62, 64, 66,67]
rfe_w40 = [ 0,  2,  3,  4,  5,  7,  9, 15, 22, 23, 24, 26, 28, 29, 32, 33, 34,
       35, 36, 38, 40, 44, 45, 47, 49, 50, 51, 52, 53, 54, 56, 57, 59, 60,
       61, 62, 64, 65, 66, 67]

rfe_c15 = [ 0,  5, 23, 24, 28, 29, 32, 33, 47, 56, 59, 60, 61, 62, 64]
rfe_c25 = [ 0,  4,  5, 15, 17, 22, 23, 24, 28, 29, 32, 33, 40, 44, 45, 47, 52, 56, 59, 60, 61, 62, 64, 66, 67]
rfe_c30 = [ 0,  4,  5,  6,  7, 15, 17, 22, 23, 24, 27, 28, 29, 31, 32, 33, 38, 40, 44, 45, 47, 52, 56, 59, 60, 61, 62, 64, 66, 67]
rfe_c35 = [ 0,  4,  5,  6,  7, 15, 17, 22, 23, 24, 27, 28, 29, 31, 32, 33, 34, 38, 40, 44, 45, 47, 50, 51, 52, 53, 56, 58, 59, 60, 61, 62, 64, 66,67]
rfe_c40 = [0,  2,  3,  4,  5,  6,  7, 15, 17, 22, 23, 24, 27, 28, 29, 31, 32, 33, 34, 35, 36, 38, 40, 44, 45, 47, 49, 50, 51, 52, 53, 54, 56, 59, 60, 61, 62, 64, 66, 67]



def get_selectedFeatures(X, indices = []):
    """
    Returns the feature vector for the given Comment
    :param X: the data part of the dataset (array of feature vectors)
    :param indices: a list of the (feature column) indices to select
    :return: numpy array of selected features
    """
    # select column indices
    return X[:, indices]

for i in range(len(fnames)):
    print str(i), fnames[i]
    rfe_c15 = [i]
    Md15 = get_selectedFeatures(m_dataset["data"], rfe_c15)
    print "m d15", compute_avg(Md15, ym, 100)

    Wd15 = get_selectedFeatures(w_dataset["data"], rfe_c15)
    print "w d15", compute_avg(Wd15, yw, 100)

    Cd15 = get_selectedFeatures(c_dataset["data"], rfe_c15)
    print "c d15", compute_avg(Cd15, yc, 100)
    print "------------------\n"
    
    


/Users/nischikata/Documents/FHHGB/PycharmProjects/AggressivenessClassification/venv/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


0 as_is___exclamation_ratio
m d15    recall 0.269586082471   precision:  0.729388547886    accuracy:  0.584324324324 f-score:  0.393669659366
[[ 11637.   1297.]
 [  9469.   3497.]]
None
w d15    recall 0.290110464557   precision:  0.730513497726    accuracy:  0.590048115477 f-score:  0.415294208292
[[ 55425.   6697.]
 [ 44424.  18154.]]
None
c d15    recall 0.285402252626   precision:  0.729203328147    accuracy:  0.587934926959 f-score:  0.410240740677
[[ 66965.   8015.]
 [ 54042.  21578.]]
None
------------------

1 as_is___long_words_count
m d15    recall 0.753438046236   precision:  0.643310761634    accuracy:  0.669420849421 f-score:  0.694032886425
[[ 7636.  5382.]
 [ 3180.  9702.]]
None
w d15    recall 0.87001744074   precision:  0.585427171953    accuracy:  0.624498797113 f-score:  0.699898636389
[[ 23474.  38664.]
 [  8161.  54401.]]
None
c d15    recall 0.855812022235   precision:  0.594788483233    accuracy:  0.63598937583 f-score:  0.701815741438
[[ 31400.  43947.]
 [ 10873

/Users/nischikata/Documents/FHHGB/PycharmProjects/AggressivenessClassification/venv/lib/python2.7/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


    recall 0.81155496358   precision:  0.516174303294    accuracy:  0.548494208494 f-score:  0.631007884457
[[  3734.   9214.]
 [  2480.  10472.]]
None
w d15    recall 0.797377862662   precision:  0.517940791228    accuracy:  0.525653568565 f-score:  0.627976376482
[[ 15689.  46459.]
 [ 12692.  49860.]]
None
c d15    recall 0.803569971744   precision:  0.520829069234    accuracy:  0.531261620186 f-score:  0.632018881769
[[ 19439.  55762.]
 [ 14830.  60569.]]
None
------------------

6 as_is___whitespace_ratio
m d15    recall 0.353135951239   precision:  0.44984794685    accuracy:  0.487606177606 f-score:  0.395667915638
[[ 8299.  4712.]
 [ 8559.  4330.]]
None
w d15    recall 0.557946719904   precision:  0.630583495299    accuracy:  0.612429831596 f-score:  0.592045516937
[[ 41534.  20595.]
 [ 27735.  34836.]]
None
c d15    recall 0.54341580421   precision:  0.616886069482    accuracy:  0.602118193891 f-score:  0.57782486981
[[ 49909.  25540.]
 [ 34381.  40770.]]
None
------------------

m d15    recall 0.630027993381   precision:  0.549481148696    accuracy:  0.559343629344 f-score:  0.587004361669
[[ 6469.  6511.]
 [ 4902.  8018.]]
None
w d15    recall 0.552894236713   precision:  0.471622362072    accuracy:  0.480850040096 f-score:  0.509034770552
[[ 26053.  36285.]
 [ 28453.  33909.]]
None
c d15    recall 0.444163224713   precision:  0.463624809622    accuracy:  0.475365205843 f-score:  0.453685403883
[[ 38760.  36581.]
 [ 42429.  32830.]]
None
------------------

22 as_is___subj_ratio
m d15    recall 0.401566786066   precision:  0.519797584573    accuracy:  0.495366795367 f-score:  0.453096412437
[[ 7841.  5149.]
 [ 7921.  4989.]]
None
w d15    recall 0.571604729298   precision:  0.507112828604    accuracy:  0.497433841219 f-score:  0.537430931747
[[ 26571.  35725.]
 [ 26945.  35459.]]
None
c d15    recall 0.536331396643   precision:  0.506208894023    accuracy:  0.49307436919 f-score:  0.520834975022
[[ 34238.  41129.]
 [ 35214.  40019.]]
None
------------------


m d15    recall 0.217158486863   precision:  0.605646253092    accuracy:  0.515714285714 f-score:  0.319690000577
[[ 10654.   2282.]
 [ 10261.   2703.]]
None
w d15    recall 0.651029164347   precision:  0.43633136088    accuracy:  0.495228548516 f-score:  0.522484373235
[[ 21571.  40659.]
 [ 22286.  40184.]]
None
c d15    recall 0.509622808817   precision:  0.403884992728    accuracy:  0.49061752988 f-score:  0.45063436587
[[ 36127.  39038.]
 [ 37675.  37760.]]
None
------------------

38 as_is___noise_count
m d15    recall 0.133026483493   precision:  0.921812526813    accuracy:  0.513938223938 f-score:  0.232500841709
[[ 11703.   1301.]
 [ 11288.   1608.]]
None
w d15    recall 0.537236644269   precision:  0.379329713284    accuracy:  0.490890136327 f-score:  0.444681000032
[[ 28067.  33916.]
 [ 29570.  33147.]]
None
c d15    recall 0.49000582993   precision:  0.562394154818    accuracy:  0.492881806109 f-score:  0.52371041158
[[ 37957.  37233.]
 [ 39139.  36271.]]
None
--------------

m d15    recall 0.14304277534   precision:  0.821929646742    accuracy:  0.553822393822 f-score:  0.243677632881
[[ 12515.    505.]
 [ 11051.   1829.]]
None
w d15    recall 0.138248999938   precision:  0.815428157219    accuracy:  0.554739374499 f-score:  0.236415701919
[[ 60582.   1944.]
 [ 53580.   8594.]]
None
c d15    recall 0.138528936225   precision:  0.820143691307    accuracy:  0.55462815405 f-score:  0.237022795573
[[ 73109.   2280.]
 [ 64793.  10418.]]
None
------------------

54 per_sent___paras_count
m d15    recall 0.297148501959   precision:  0.573227421474    accuracy:  0.538494208494 f-score:  0.391402530761
[[ 10125.   2870.]
 [  9083.   3822.]]
None
w d15    recall 0.512487640316   precision:  0.605370769565    accuracy:  0.583801122694 f-score:  0.555070363954
[[ 40906.  21358.]
 [ 30542.  31894.]]
None
c d15    recall 0.52877756683   precision:  0.587755246062    accuracy:  0.577928286853 f-score:  0.556708742127
[[ 47134.  28001.]
 [ 35563.  39902.]]
None
---------

In [32]:
rfe_c15 = [0,1,5,7,10,27, 34,67, 56, 40, 44, 43]

# Lasso: 
rfe_c15 = [ 4,  5,  6, 11, 15, 22, 24, 26, 28, 29, 32, 35, 47, 49, 58, 59, 60,
       61, 62, 63, 64, 67]
rfe_c15 = [ 5, 11, 22, 24, 26, 28, 29, 32, 35, 49, 59, 60, 61, 62, 63, 64, 67]
rfe_c15 = [ 5,  6, 11, 22, 24, 26, 28, 29, 32, 35, 47, 49, 58, 59, 60, 61, 62,
       63, 64, 67]
rfe_c15 = [ 5, 11, 22, 24, 26, 28, 29, 32, 35, 47, 49, 58, 59, 60, 61, 62, 63,
       64, 67] #LassoLars
rfe_c15 = [ 5,  6, 11, 22, 24, 26, 28, 29, 32, 35, 47, 49, 58, 59, 60, 61, 62,
       63, 64, 67] #ElasticNet

rfe_c15 = [60, 56, 40, 24, 61, 62,  4,  0, 32, 33,  7, 51, 13, 23,  1, 11,  6,
       19, 26, 20, 35, 22, 12,  5, 59, 54, 18,  8, 49, 43] #random forest 30 best

rfe_c15 = [60, 56, 40, 24, 61, 62,  4,  0, 32, 33,  7, 51, 13, 23,  1, 11,  6,
       19, 26, 20] #random forest 20 best ziemlich gut bei w und c

rfe_c15 = [ 0,  4,  5,  7, 23, 24, 28, 32, 33, 44, 47, 49, 53, 59, 60, 61, 62,
       64, 67]

rfe_c15 = [ 0,  1,  2,  3,  5,  8, 11, 23, 24, 34, 35, 40, 41, 42, 43, 46, 47,
       52, 53, 54, 56, 58, 59, 61, 62]

Md15 = get_selectedFeatures(m_dataset["data"], rfe_c15)
print "m d15", compute_avg(Md15, ym, 100)

Wd15 = get_selectedFeatures(w_dataset["data"], rfe_c15)
print "w d15", compute_avg(Wd15, yw, 100)

Cd15 = get_selectedFeatures(c_dataset["data"], rfe_c15)
print "c d15", compute_avg(Cd15, yc, 100)
print "------------------\n"

m d15    recall 0.774425074196   precision:  0.803393012815    accuracy:  0.793204633205 f-score:  0.788643125186
[[ 10578.   2450.]
 [  2906.   9966.]]
None
w d15    recall 0.778650881369   precision:  0.943080118012    accuracy:  0.865429029671 f-score:  0.85301381616
[[ 59233.   2943.]
 [ 13838.  48686.]]
None
c d15    recall 0.745025208245   precision:  0.924072104591    accuracy:  0.841792828685 f-score:  0.824945324472
[[ 70662.   4620.]
 [ 19206.  56112.]]
None
------------------



In [33]:
len([ 0,  1,  2,  3,  5,  8, 11, 23, 24, 34, 35, 40, 41, 42, 43, 46, 47,
       52, 53, 54, 56, 58, 59, 61, 62])

25